services:
  backend-app:
    build:
      image: task_backend_image
      context: .
      dockerfile: Dockerfile
    container_name: task_backend_container
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
